-- ==============================================================
-- PATCH: Re-parent OTHERS nodes ให้เป็น child ของ region ที่ตัวเองสังกัด
-- (เดิมเป็น sibling/root → ยอด region ไม่รวม OTHERS ในทุกหน้ารายงาน)
-- ครอบคลุม 16 nodes: 4 nodes × 4 groups (STD_GOV, STD_TAT, ALL_GOV, ALL_TAT)
-- ไม่แตะ OTHER IN ASIA (GOV) — ไม่มี region "ASIA" เดี่ยว และถูกรวมใน
-- ASIA AND THE PACIFIC อยู่แล้ว
-- ใช้ name-based matching (กัน NODE_ID เลื่อนระหว่าง dev/prod)
-- Created: 2026-06-04
-- ==============================================================

-- ---------- BEFORE ----------
SELECT G.GROUP_CODE, N.NODE_ID, N.NAME_EN, N.PARENT_NODE_ID
FROM MD_COUNTRY_GROUP_NODE N
JOIN MD_COUNTRY_GROUP G ON G.GROUP_ID = N.GROUP_ID
WHERE N.IS_OTHERS = 'Y' AND N.NODE_TYPE = 'REGION'
ORDER BY G.GROUP_ID, N.SORT_ORDER;

-- ---------- GOV groups (STD_GOV + ALL_GOV): 8 nodes ----------
UPDATE MD_COUNTRY_GROUP_NODE N
SET N.PARENT_NODE_ID = (SELECT P.NODE_ID FROM MD_COUNTRY_GROUP_NODE P
    WHERE P.GROUP_ID = N.GROUP_ID AND P.NODE_TYPE = 'REGION'
      AND P.IS_OTHERS = 'N' AND P.NAME_EN = 'OCEANIA')
WHERE N.NODE_TYPE = 'REGION' AND N.IS_OTHERS = 'Y' AND N.NAME_EN = 'OTHER IN OCEANIA'
  AND N.GROUP_ID IN (SELECT GROUP_ID FROM MD_COUNTRY_GROUP WHERE GROUP_CODE IN ('STD_GOV','ALL_GOV'));

UPDATE MD_COUNTRY_GROUP_NODE N
SET N.PARENT_NODE_ID = (SELECT P.NODE_ID FROM MD_COUNTRY_GROUP_NODE P
    WHERE P.GROUP_ID = N.GROUP_ID AND P.NODE_TYPE = 'REGION'
      AND P.IS_OTHERS = 'N' AND P.NAME_EN = 'AMERICA')
WHERE N.NODE_TYPE = 'REGION' AND N.IS_OTHERS = 'Y' AND N.NAME_EN = 'OTHER IN AMERICA'
  AND N.GROUP_ID IN (SELECT GROUP_ID FROM MD_COUNTRY_GROUP WHERE GROUP_CODE IN ('STD_GOV','ALL_GOV'));

UPDATE MD_COUNTRY_GROUP_NODE N
SET N.PARENT_NODE_ID = (SELECT P.NODE_ID FROM MD_COUNTRY_GROUP_NODE P
    WHERE P.GROUP_ID = N.GROUP_ID AND P.NODE_TYPE = 'REGION'
      AND P.IS_OTHERS = 'N' AND P.NAME_EN = 'MIDDLE EAST')
WHERE N.NODE_TYPE = 'REGION' AND N.IS_OTHERS = 'Y' AND N.NAME_EN = 'OTHER IN MIDDLE EAST'
  AND N.GROUP_ID IN (SELECT GROUP_ID FROM MD_COUNTRY_GROUP WHERE GROUP_CODE IN ('STD_GOV','ALL_GOV'));

UPDATE MD_COUNTRY_GROUP_NODE N
SET N.PARENT_NODE_ID = (SELECT P.NODE_ID FROM MD_COUNTRY_GROUP_NODE P
    WHERE P.GROUP_ID = N.GROUP_ID AND P.NODE_TYPE = 'REGION'
      AND P.IS_OTHERS = 'N' AND P.NAME_EN = 'AFRICA')
WHERE N.NODE_TYPE = 'REGION' AND N.IS_OTHERS = 'Y' AND N.NAME_EN = 'OTHER IN AFRICA'
  AND N.GROUP_ID IN (SELECT GROUP_ID FROM MD_COUNTRY_GROUP WHERE GROUP_CODE IN ('STD_GOV','ALL_GOV'));

-- ---------- TAT groups (STD_TAT + ALL_TAT): 8 nodes ----------
UPDATE MD_COUNTRY_GROUP_NODE N
SET N.PARENT_NODE_ID = (SELECT P.NODE_ID FROM MD_COUNTRY_GROUP_NODE P
    WHERE P.GROUP_ID = N.GROUP_ID AND P.NODE_TYPE = 'REGION'
      AND P.IS_OTHERS = 'N' AND P.NAME_EN = 'EAST ASIA')
WHERE N.NODE_TYPE = 'REGION' AND N.IS_OTHERS = 'Y' AND N.NAME_EN = 'OTHERS IN EAST ASIA'
  AND N.GROUP_ID IN (SELECT GROUP_ID FROM MD_COUNTRY_GROUP WHERE GROUP_CODE IN ('STD_TAT','ALL_TAT'));

UPDATE MD_COUNTRY_GROUP_NODE N
SET N.PARENT_NODE_ID = (SELECT P.NODE_ID FROM MD_COUNTRY_GROUP_NODE P
    WHERE P.GROUP_ID = N.GROUP_ID AND P.NODE_TYPE = 'REGION'
      AND P.IS_OTHERS = 'N' AND P.NAME_EN = 'ASEAN, SOUTH ASIA, SOUTH PACIFIC')
WHERE N.NODE_TYPE = 'REGION' AND N.IS_OTHERS = 'Y'
  AND N.NAME_EN = 'OTHERS IN ASEAN, SOUTH ASIA, SOUTH PACIFIC'
  AND N.GROUP_ID IN (SELECT GROUP_ID FROM MD_COUNTRY_GROUP WHERE GROUP_CODE IN ('STD_TAT','ALL_TAT'));

UPDATE MD_COUNTRY_GROUP_NODE N
SET N.PARENT_NODE_ID = (SELECT P.NODE_ID FROM MD_COUNTRY_GROUP_NODE P
    WHERE P.GROUP_ID = N.GROUP_ID AND P.NODE_TYPE = 'REGION'
      AND P.IS_OTHERS = 'N' AND P.NAME_EN = 'EUROPE')
WHERE N.NODE_TYPE = 'REGION' AND N.IS_OTHERS = 'Y' AND N.NAME_EN = 'OTHERS IN EUROPE'
  AND N.GROUP_ID IN (SELECT GROUP_ID FROM MD_COUNTRY_GROUP WHERE GROUP_CODE IN ('STD_TAT','ALL_TAT'));

UPDATE MD_COUNTRY_GROUP_NODE N
SET N.PARENT_NODE_ID = (SELECT P.NODE_ID FROM MD_COUNTRY_GROUP_NODE P
    WHERE P.GROUP_ID = N.GROUP_ID AND P.NODE_TYPE = 'REGION'
      AND P.IS_OTHERS = 'N' AND P.NAME_EN = 'THE AMERICAS, THE MIDDLE EAST AND AFRICA')
WHERE N.NODE_TYPE = 'REGION' AND N.IS_OTHERS = 'Y'
  AND N.NAME_EN = 'OTHERS IN THE AMERICAS, THE MIDDLE EAST AND AFRICA'
  AND N.GROUP_ID IN (SELECT GROUP_ID FROM MD_COUNTRY_GROUP WHERE GROUP_CODE IN ('STD_TAT','ALL_TAT'));

COMMIT;

-- ---------- AFTER (ทุก OTHERS ต้องมี PARENT_NAME = region ที่สังกัด) ----------
SELECT G.GROUP_CODE, N.NODE_ID, N.NAME_EN, N.PARENT_NODE_ID, P.NAME_EN AS PARENT_NAME
FROM MD_COUNTRY_GROUP_NODE N
JOIN MD_COUNTRY_GROUP G ON G.GROUP_ID = N.GROUP_ID
LEFT JOIN MD_COUNTRY_GROUP_NODE P ON P.NODE_ID = N.PARENT_NODE_ID
WHERE N.IS_OTHERS = 'Y' AND N.NODE_TYPE = 'REGION'
ORDER BY G.GROUP_ID, N.SORT_ORDER;
-- Expected: ไม่มี PARENT_NODE_ID เป็น NULL · GOV: OTHER IN X → X (ยกเว้น OTHER IN
-- ASIA → ASIA AND THE PACIFIC คงเดิม) · TAT: OTHERS IN X → X
