-- ==============================================================
-- PATCH: Re-parent ASIA AND SOUTH PACIFIC (STD_TAT + ALL_TAT)
-- ทำให้โครงสร้าง ททท สมบูรณ์ (EAST ASIA + ASEAN.. เป็น child ของ ASIA AND SOUTH PACIFIC)
-- รันหลังจาก md_country_group_deploy.sql
-- ==============================================================

-- STD_TAT: ASIA AND SOUTH PACIFIC (node 2694) เป็น parent ของ 4 region
UPDATE MD_COUNTRY_GROUP_NODE SET IS_SUMMARY = 'Y'   WHERE NODE_ID = 2694; -- ASIA AND SOUTH PACIFIC
UPDATE MD_COUNTRY_GROUP_NODE SET PARENT_NODE_ID = 2694 WHERE NODE_ID = 2695; -- EAST ASIA
UPDATE MD_COUNTRY_GROUP_NODE SET PARENT_NODE_ID = 2694 WHERE NODE_ID = 2708; -- OTHERS IN EAST ASIA
UPDATE MD_COUNTRY_GROUP_NODE SET PARENT_NODE_ID = 2694 WHERE NODE_ID = 2709; -- ASEAN, SOUTH ASIA, SOUTH PACIFIC
UPDATE MD_COUNTRY_GROUP_NODE SET PARENT_NODE_ID = 2694 WHERE NODE_ID = 2734; -- OTHERS IN ASEAN, SOUTH ASIA, SOUTH PACIFIC

-- ALL_TAT: ASIA AND SOUTH PACIFIC (node 3129) เป็น parent ของ 4 region
UPDATE MD_COUNTRY_GROUP_NODE SET IS_SUMMARY = 'Y'   WHERE NODE_ID = 3129; -- ASIA AND SOUTH PACIFIC
UPDATE MD_COUNTRY_GROUP_NODE SET PARENT_NODE_ID = 3129 WHERE NODE_ID = 3130; -- EAST ASIA
UPDATE MD_COUNTRY_GROUP_NODE SET PARENT_NODE_ID = 3129 WHERE NODE_ID = 3143; -- OTHERS IN EAST ASIA
UPDATE MD_COUNTRY_GROUP_NODE SET PARENT_NODE_ID = 3129 WHERE NODE_ID = 3149; -- ASEAN, SOUTH ASIA, SOUTH PACIFIC
UPDATE MD_COUNTRY_GROUP_NODE SET PARENT_NODE_ID = 3129 WHERE NODE_ID = 3174; -- OTHERS IN ASEAN, SOUTH ASIA, SOUTH PACIFIC

COMMIT;

-- Verify: แต่ละ group ควรมี 2 summary regions (ASIA AND SOUTH PACIFIC + EUROPE AMERICA ME AFRICA)
SELECT G.GROUP_CODE, N.NAME_EN, N.IS_SUMMARY
FROM MD_COUNTRY_GROUP G
JOIN MD_COUNTRY_GROUP_NODE N ON N.GROUP_ID = G.GROUP_ID
WHERE G.GROUP_CODE IN ('STD_TAT','ALL_TAT')
  AND N.NODE_TYPE = 'REGION'
  AND N.IS_SUMMARY = 'Y'
ORDER BY G.GROUP_CODE, N.SORT_ORDER;
-- Expected 4 rows (2 × 2 groups)
