-- =====================================================================
-- md_std_tat_others_fill.sql
-- เพิ่ม 84 ประเทศที่มี arrival ปี 2024 ลงใน OTHERS buckets ของ STD_TAT
-- Schema: Oracle TAT (139.180.208.163:1521 SID=XE schema=TAT)
-- รันทั้งไฟล์ครั้งเดียว (มี COMMIT ในตัว + BEFORE/AFTER verify)
--
-- เป้าหมาย: nation_compare 08-09-2024 STD_TAT 72,758 → 72,955 (= ALL_TAT)
--
-- โครงสร้าง STD_TAT มี 4 OTHERS regions ว่างเปล่าอยู่แล้ว:
--   NODE=125 'OTHERS IN EAST ASIA'                              (parent=111)
--   NODE=151 'OTHERS IN ASEAN, SOUTH ASIA, SOUTH PACIFIC'       (parent=111)
--   NODE=211 'OTHERS IN EUROPE'                                 (parent=152)
--   NODE=261 'OTHERS IN THE AMERICAS, THE MIDDLE EAST AND AFRICA' (parent=152)
--
-- NODE_ID range ใช้: 900-983 (max ปัจจุบัน = 861)
-- SORT_ORDER range: ต่อจาก parent (เริ่มที่ 16, 42, 102, 152 ของ STD_TAT structure)
-- GROUP_ID = 2 (STD_TAT)
-- =====================================================================

-- ====== BEFORE: ตรวจสถานะ OTHERS regions ของ STD_TAT (ต้องเห็น 4 row, NC=0 ทุกตัว) ======
SELECT 'BEFORE - STD_TAT OTHERS regions' AS phase, NODE_ID, NAME_EN,
       (SELECT COUNT(*) FROM MD_COUNTRY_GROUP_NODE c
        WHERE c.PARENT_NODE_ID = n.NODE_ID AND c.NODE_TYPE = 'COUNTRY') AS NC
FROM MD_COUNTRY_GROUP_NODE n
WHERE n.NODE_ID IN (125, 151, 211, 261)
ORDER BY n.NODE_ID;

-- ====== BACKUP (optional) ======
-- CREATE TABLE MD_COUNTRY_GROUP_NODE_BAK_STDTAT_OTHERS AS SELECT * FROM MD_COUNTRY_GROUP_NODE;

-- =====================================================================
-- INSERT: 84 country nodes ลง OTHERS buckets
-- format: (NODE_ID, GROUP_ID=2, PARENT, 'COUNTRY', NAME, NULL, COUNTRY_ID, SORT, 'N', 'N')
-- =====================================================================

-- ---------- OTHERS IN EAST ASIA (parent=125) — 2 ประเทศ ----------
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (900, 2, 125, 'COUNTRY', 'DPR. KOREA', NULL, 159, 16, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (901, 2, 125, 'COUNTRY', 'TIMOR-LESTE', NULL, 151, 17, 'N', 'N');

-- ---------- OTHERS IN ASEAN, SOUTH ASIA, SOUTH PACIFIC (parent=151) — 16 ประเทศ ----------
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (902, 2, 151, 'COUNTRY', 'AFGHANISTAN', NULL, 163, 42, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (903, 2, 151, 'COUNTRY', 'FIJI', NULL, 241, 43, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (904, 2, 151, 'COUNTRY', 'FRENCH POLYNESIA', NULL, 256, 44, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (905, 2, 151, 'COUNTRY', 'KIRIBATI', NULL, 249, 45, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (906, 2, 151, 'COUNTRY', 'MARSHALL ISLANDS', NULL, 251, 46, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (907, 2, 151, 'COUNTRY', 'MICRONESIA', NULL, 242, 47, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (908, 2, 151, 'COUNTRY', 'NAURU', NULL, 270, 48, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (909, 2, 151, 'COUNTRY', 'NORTHERN MARIANA ISLANDS', NULL, 260, 49, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (910, 2, 151, 'COUNTRY', 'PALAU', NULL, 272, 50, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (911, 2, 151, 'COUNTRY', 'PAPUA NEW GUINEA', NULL, 243, 51, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (912, 2, 151, 'COUNTRY', 'SAMOA', NULL, 244, 52, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (913, 2, 151, 'COUNTRY', 'SOLOMON ISLANDS', NULL, 245, 53, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (914, 2, 151, 'COUNTRY', 'SOUTH GEORGIA AND SOUTH SANDWICH ISL', NULL, 176, 54, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (915, 2, 151, 'COUNTRY', 'TONGA', NULL, 246, 55, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (916, 2, 151, 'COUNTRY', 'TUVALU', NULL, 273, 56, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (917, 2, 151, 'COUNTRY', 'VANUATU', NULL, 250, 57, 'N', 'N');

-- ---------- OTHERS IN EUROPE (parent=211) — 4 ประเทศ ----------
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (918, 2, 211, 'COUNTRY', 'ANDORRA', NULL, 95, 102, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (919, 2, 211, 'COUNTRY', 'MALTA', NULL, 97, 103, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (920, 2, 211, 'COUNTRY', 'SAN MARINO', NULL, 99, 104, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (921, 2, 211, 'COUNTRY', 'TAJIKISTAN', NULL, 59, 105, 'N', 'N');

-- ---------- OTHERS IN THE AMERICAS, THE MIDDLE EAST AND AFRICA (parent=261) — 62 ประเทศ ----------
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (922, 2, 261, 'COUNTRY', 'ANGOLA', NULL, 179, 152, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (923, 2, 261, 'COUNTRY', 'ANTIGUA AND BARBUDA', NULL, 21, 153, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (924, 2, 261, 'COUNTRY', 'BARBADOS', NULL, 10, 154, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (925, 2, 261, 'COUNTRY', 'BENIN', NULL, 189, 155, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (926, 2, 261, 'COUNTRY', 'BOTSWANA', NULL, 224, 156, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (927, 2, 261, 'COUNTRY', 'BURKINA FASO', NULL, 201, 157, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (928, 2, 261, 'COUNTRY', 'BURUNDI', NULL, 207, 158, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (929, 2, 261, 'COUNTRY', 'CAMEROON', NULL, 181, 159, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (930, 2, 261, 'COUNTRY', 'CAPE VERDE', NULL, 202, 160, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (931, 2, 261, 'COUNTRY', 'CENTRAL AFRICAN REPUBLIC', NULL, 186, 161, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (932, 2, 261, 'COUNTRY', 'CHAD', NULL, 182, 162, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (933, 2, 261, 'COUNTRY', 'COMOROS', NULL, 221, 163, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (934, 2, 261, 'COUNTRY', 'CONGO', NULL, 183, 164, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (935, 2, 261, 'COUNTRY', 'CONGO REPUBLIC', NULL, 184, 165, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (936, 2, 261, 'COUNTRY', 'CUBA', NULL, 3, 166, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (937, 2, 261, 'COUNTRY', 'DJIBOUTI', NULL, 220, 167, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (938, 2, 261, 'COUNTRY', 'DOMINICA', NULL, 15, 168, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (939, 2, 261, 'COUNTRY', 'DOMINICAN REPUBLIC', NULL, 4, 169, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (940, 2, 261, 'COUNTRY', 'EQUATORIAL GUINEA', NULL, 187, 170, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (941, 2, 261, 'COUNTRY', 'ERITREA', NULL, 206, 171, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (942, 2, 261, 'COUNTRY', 'GABON', NULL, 180, 172, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (943, 2, 261, 'COUNTRY', 'GAMBIA,THE', NULL, 190, 173, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (944, 2, 261, 'COUNTRY', 'GHANA', NULL, 191, 174, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (945, 2, 261, 'COUNTRY', 'GREENLAND', NULL, 109, 175, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (946, 2, 261, 'COUNTRY', 'GRENADA', NULL, 5, 176, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (947, 2, 261, 'COUNTRY', 'GUINEA', NULL, 192, 177, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (948, 2, 261, 'COUNTRY', 'GUINEA BISSAU', NULL, 205, 178, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (949, 2, 261, 'COUNTRY', 'HAITI', NULL, 7, 179, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (950, 2, 261, 'COUNTRY', 'IVORY COAST', NULL, 193, 180, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (951, 2, 261, 'COUNTRY', 'JAMAICA', NULL, 8, 181, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (952, 2, 261, 'COUNTRY', 'LESOTHO', NULL, 227, 182, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (953, 2, 261, 'COUNTRY', 'LIBERIA', NULL, 194, 183, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (954, 2, 261, 'COUNTRY', 'MADAGASCAR', NULL, 210, 184, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (955, 2, 261, 'COUNTRY', 'MALAWI', NULL, 211, 185, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (956, 2, 261, 'COUNTRY', 'MALI', NULL, 195, 186, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (957, 2, 261, 'COUNTRY', 'MAURITANIA', NULL, 203, 187, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (958, 2, 261, 'COUNTRY', 'MAURITIUS', NULL, 212, 188, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (959, 2, 261, 'COUNTRY', 'MAYOTTE', NULL, 232, 189, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (960, 2, 261, 'COUNTRY', 'MOZAMBIQUE', NULL, 213, 190, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (961, 2, 261, 'COUNTRY', 'NAMIBIA', NULL, 226, 191, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (962, 2, 261, 'COUNTRY', 'NETHERLANDS ANTILLES', NULL, 135, 192, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (963, 2, 261, 'COUNTRY', 'NIGER', NULL, 196, 193, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (964, 2, 261, 'COUNTRY', 'RWANDA', NULL, 214, 194, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (965, 2, 261, 'COUNTRY', 'SAINT HELENA', NULL, 223, 195, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (966, 2, 261, 'COUNTRY', 'SAINT KITTS AND NEVIS', NULL, 18, 196, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (967, 2, 261, 'COUNTRY', 'SAINT LUCIA', NULL, 17, 197, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (968, 2, 261, 'COUNTRY', 'SAINT PIERRE AND MIQUELON', NULL, 140, 198, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (969, 2, 261, 'COUNTRY', 'SAINT VINCENT AND THE GRENADINES', NULL, 19, 199, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (970, 2, 261, 'COUNTRY', 'SAO TOME AND PRINCIPE', NULL, 178, 200, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (971, 2, 261, 'COUNTRY', 'SENEGAL', NULL, 198, 201, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (972, 2, 261, 'COUNTRY', 'SEYCHELLES', NULL, 215, 202, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (973, 2, 261, 'COUNTRY', 'SIERRA LEONE', NULL, 199, 203, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (974, 2, 261, 'COUNTRY', 'SOMALIA', NULL, 216, 204, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (975, 2, 261, 'COUNTRY', 'SUDAN', NULL, 235, 205, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (976, 2, 261, 'COUNTRY', 'SWAZILAND', NULL, 228, 206, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (977, 2, 261, 'COUNTRY', 'TANZANIA', NULL, 217, 207, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (978, 2, 261, 'COUNTRY', 'TOGO', NULL, 200, 208, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (979, 2, 261, 'COUNTRY', 'TRINIDAD AND TOBAGO', NULL, 12, 209, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (980, 2, 261, 'COUNTRY', 'TURKS AND CAICOS ISLANDS', NULL, 24, 210, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (981, 2, 261, 'COUNTRY', 'UGANDA', NULL, 218, 211, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (982, 2, 261, 'COUNTRY', 'ZAMBIA', NULL, 219, 212, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (983, 2, 261, 'COUNTRY', 'ZIMBABWE', NULL, 185, 213, 'N', 'N');

COMMIT;

-- =====================================================================
-- AFTER: ตรวจสอบหลัง INSERT
-- =====================================================================

-- 1) นับ COUNTRY ใน 4 OTHERS bucket (ต้องได้: 2, 16, 4, 62)
SELECT 'AFTER - OTHERS country counts' AS phase, NODE_ID, NAME_EN,
       (SELECT COUNT(*) FROM MD_COUNTRY_GROUP_NODE c
        WHERE c.PARENT_NODE_ID = n.NODE_ID AND c.NODE_TYPE = 'COUNTRY') AS NC
FROM MD_COUNTRY_GROUP_NODE n
WHERE n.NODE_ID IN (125, 151, 211, 261)
ORDER BY n.NODE_ID;

-- 2) นับ country ทั้งหมดใน STD_TAT (ต้องได้ 121 + 84 = 205)
SELECT 'AFTER - STD_TAT total country count' AS phase, COUNT(DISTINCT n.COUNTRY_ID) AS CNT
FROM MD_COUNTRY_GROUP g
JOIN MD_COUNTRY_GROUP_NODE n ON n.GROUP_ID = g.GROUP_ID
WHERE g.GROUP_CODE = 'STD_TAT' AND n.NODE_TYPE = 'COUNTRY' AND n.COUNTRY_ID IS NOT NULL;

-- 3) ไม่มี duplicate COUNTRY_ID ใน STD_TAT (ต้องได้ 0 rows)
SELECT 'AFTER - STD_TAT duplicates' AS phase, n.COUNTRY_ID, COUNT(*) AS CNT
FROM MD_COUNTRY_GROUP g
JOIN MD_COUNTRY_GROUP_NODE n ON n.GROUP_ID = g.GROUP_ID
WHERE g.GROUP_CODE = 'STD_TAT' AND n.NODE_TYPE = 'COUNTRY' AND n.COUNTRY_ID IS NOT NULL
GROUP BY n.COUNTRY_ID
HAVING COUNT(*) > 1;
