-- =====================================================================
-- md_std_gov_others_fill.sql
-- เพิ่ม 113 ประเทศที่มี arrival ปี 2024 ลงใน OTHERS buckets ของ STD_GOV
-- Schema: Oracle TAT (139.180.208.163:1521 SID=XE schema=TAT)
-- รันทั้งไฟล์ครั้งเดียว (มี COMMIT ในตัว + BEFORE/AFTER verify)
--
-- เป้าหมาย: nation_compare 08-09-2024 STD_GOV 72,681 → 72,955 (= ALL/STD_TAT)
--
-- โครงสร้าง STD_GOV มี 6 OTHERS regions ว่างเปล่าอยู่แล้ว:
--   NODE=30  'OTHER IN ASIA'        (parent=1, ASIA AND THE PACIFIC)
--   NODE=34  'OTHER IN OCEANIA'     (parent=1)
--   NODE=79  'OTHER IN EUROPE'      (parent=35, EUROPE)
--   NODE=90  'OTHER IN AMERICA'     (parent=ROOT)
--   NODE=103 'OTHER IN MIDDLE EAST' (parent=ROOT)
--   NODE=110 'OTHER IN AFRICA'      (parent=ROOT)
--
-- NODE_ID range: 1000-1112 (max ปัจจุบัน หลัง STD_TAT fill = 983)
-- GROUP_ID = 1 (STD_GOV)
-- =====================================================================

-- ====== BEFORE: ตรวจสถานะ OTHERS regions (ต้องเห็น 6 row, NC=0 ทุกตัว) ======
SELECT 'BEFORE - STD_GOV OTHERS regions' AS phase, NODE_ID, NAME_EN,
       (SELECT COUNT(*) FROM MD_COUNTRY_GROUP_NODE c
        WHERE c.PARENT_NODE_ID = n.NODE_ID AND c.NODE_TYPE = 'COUNTRY') AS NC
FROM MD_COUNTRY_GROUP_NODE n
WHERE n.NODE_ID IN (30, 34, 79, 90, 103, 110)
ORDER BY n.NODE_ID;

-- ====== BACKUP (optional) ======
-- CREATE TABLE MD_COUNTRY_GROUP_NODE_BAK_STDGOV_OTHERS AS SELECT * FROM MD_COUNTRY_GROUP_NODE;

-- ---------- OTHER IN ASIA (parent=30) — 2 ประเทศ ----------
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1000, 1, 30, 'COUNTRY', 'AFGHANISTAN', NULL, 163, 200, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1001, 1, 30, 'COUNTRY', 'TIMOR-LESTE', NULL, 151, 201, 'N', 'N');

-- ---------- OTHER IN OCEANIA (parent=34) — 14 ประเทศ ----------
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1002, 1, 34, 'COUNTRY', 'FIJI', NULL, 241, 210, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1003, 1, 34, 'COUNTRY', 'FRENCH POLYNESIA', NULL, 256, 211, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1004, 1, 34, 'COUNTRY', 'KIRIBATI', NULL, 249, 212, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1005, 1, 34, 'COUNTRY', 'MARSHALL ISLANDS', NULL, 251, 213, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1006, 1, 34, 'COUNTRY', 'MICRONESIA', NULL, 242, 214, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1007, 1, 34, 'COUNTRY', 'NAURU', NULL, 270, 215, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1008, 1, 34, 'COUNTRY', 'NORTHERN MARIANA ISLANDS', NULL, 260, 216, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1009, 1, 34, 'COUNTRY', 'PALAU', NULL, 272, 217, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1010, 1, 34, 'COUNTRY', 'PAPUA NEW GUINEA', NULL, 243, 218, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1011, 1, 34, 'COUNTRY', 'SAMOA', NULL, 244, 219, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1012, 1, 34, 'COUNTRY', 'SOLOMON ISLANDS', NULL, 245, 220, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1013, 1, 34, 'COUNTRY', 'TONGA', NULL, 246, 221, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1014, 1, 34, 'COUNTRY', 'TUVALU', NULL, 273, 222, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1015, 1, 34, 'COUNTRY', 'VANUATU', NULL, 250, 223, 'N', 'N');

-- ---------- OTHER IN EUROPE (parent=79) — 15 ประเทศ ----------
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1016, 1, 79, 'COUNTRY', 'ALBANIA', NULL, 94, 230, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1017, 1, 79, 'COUNTRY', 'ANDORRA', NULL, 95, 231, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1018, 1, 79, 'COUNTRY', 'ARMENIA', NULL, 51, 232, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1019, 1, 79, 'COUNTRY', 'AZERBAIJAN', NULL, 52, 233, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1020, 1, 79, 'COUNTRY', 'BOSNIA AND HERZEGOVINA', NULL, 83, 234, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1021, 1, 79, 'COUNTRY', 'GEORGIA', NULL, 54, 235, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1022, 1, 79, 'COUNTRY', 'LIECHTENSTEIN', NULL, 44, 236, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1023, 1, 79, 'COUNTRY', 'MACEDONIA', NULL, 85, 237, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1024, 1, 79, 'COUNTRY', 'MALTA', NULL, 97, 238, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1025, 1, 79, 'COUNTRY', 'MOLDOVA', NULL, 57, 239, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1026, 1, 79, 'COUNTRY', 'MONACO', NULL, 98, 240, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1027, 1, 79, 'COUNTRY', 'MONTENEGRO', NULL, 42, 241, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1028, 1, 79, 'COUNTRY', 'SAN MARINO', NULL, 99, 242, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1029, 1, 79, 'COUNTRY', 'TAJIKISTAN', NULL, 59, 243, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1030, 1, 79, 'COUNTRY', 'TURKMENISTAN', NULL, 58, 244, 'N', 'N');

-- ---------- OTHER IN AMERICA (parent=90) — 31 ประเทศ ----------
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1031, 1, 90, 'COUNTRY', 'ANTIGUA AND BARBUDA', NULL, 21, 250, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1032, 1, 90, 'COUNTRY', 'BAHAMAS,THE', NULL, 2, 251, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1033, 1, 90, 'COUNTRY', 'BARBADOS', NULL, 10, 252, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1034, 1, 90, 'COUNTRY', 'BELIZE', NULL, 110, 253, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1035, 1, 90, 'COUNTRY', 'BOLIVIA', NULL, 118, 254, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1036, 1, 90, 'COUNTRY', 'COSTA RICA', NULL, 111, 255, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1037, 1, 90, 'COUNTRY', 'CUBA', NULL, 3, 256, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1038, 1, 90, 'COUNTRY', 'DOMINICA', NULL, 15, 257, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1039, 1, 90, 'COUNTRY', 'DOMINICAN REPUBLIC', NULL, 4, 258, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1040, 1, 90, 'COUNTRY', 'ECUADOR', NULL, 122, 259, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1041, 1, 90, 'COUNTRY', 'EL SALVADOR', NULL, 113, 260, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1042, 1, 90, 'COUNTRY', 'GREENLAND', NULL, 109, 261, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1043, 1, 90, 'COUNTRY', 'GRENADA', NULL, 5, 262, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1044, 1, 90, 'COUNTRY', 'GUATEMALA', NULL, 112, 263, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1045, 1, 90, 'COUNTRY', 'GUYANA', NULL, 123, 264, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1046, 1, 90, 'COUNTRY', 'HAITI', NULL, 7, 265, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1047, 1, 90, 'COUNTRY', 'HONDURAS', NULL, 114, 266, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1048, 1, 90, 'COUNTRY', 'JAMAICA', NULL, 8, 267, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1049, 1, 90, 'COUNTRY', 'NETHERLANDS ANTILLES', NULL, 135, 268, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1050, 1, 90, 'COUNTRY', 'NICARAGUA', NULL, 115, 269, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1051, 1, 90, 'COUNTRY', 'PANAMA', NULL, 116, 270, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1052, 1, 90, 'COUNTRY', 'PARAGUAY', NULL, 124, 271, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1053, 1, 90, 'COUNTRY', 'PUERTO RICO', NULL, 9, 272, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1054, 1, 90, 'COUNTRY', 'SAINT KITTS AND NEVIS', NULL, 18, 273, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1055, 1, 90, 'COUNTRY', 'SAINT LUCIA', NULL, 17, 274, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1056, 1, 90, 'COUNTRY', 'SAINT PIERRE AND MIQUELON', NULL, 140, 275, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1057, 1, 90, 'COUNTRY', 'SAINT VINCENT AND THE GRENADINES', NULL, 19, 276, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1058, 1, 90, 'COUNTRY', 'SURINAME', NULL, 126, 277, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1059, 1, 90, 'COUNTRY', 'TRINIDAD AND TOBAGO', NULL, 12, 278, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1060, 1, 90, 'COUNTRY', 'TURKS AND CAICOS ISLANDS', NULL, 24, 279, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1061, 1, 90, 'COUNTRY', 'VENEZUELA', NULL, 128, 280, 'N', 'N');

-- ---------- OTHER IN MIDDLE EAST (parent=103) — 3 ประเทศ ----------
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1062, 1, 103, 'COUNTRY', 'LIBYA', NULL, 40, 290, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1063, 1, 103, 'COUNTRY', 'PALESTINE', NULL, 34, 291, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1064, 1, 103, 'COUNTRY', 'SYRIA', NULL, 38, 292, 'N', 'N');

-- ---------- OTHER IN AFRICA (parent=110) — 48 ประเทศ ----------
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1065, 1, 110, 'COUNTRY', 'ALGERIA', NULL, 233, 300, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1066, 1, 110, 'COUNTRY', 'ANGOLA', NULL, 179, 301, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1067, 1, 110, 'COUNTRY', 'BENIN', NULL, 189, 302, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1068, 1, 110, 'COUNTRY', 'BOTSWANA', NULL, 224, 303, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1069, 1, 110, 'COUNTRY', 'BURKINA FASO', NULL, 201, 304, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1070, 1, 110, 'COUNTRY', 'BURUNDI', NULL, 207, 305, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1071, 1, 110, 'COUNTRY', 'CAMEROON', NULL, 181, 306, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1072, 1, 110, 'COUNTRY', 'CAPE VERDE', NULL, 202, 307, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1073, 1, 110, 'COUNTRY', 'CENTRAL AFRICAN REPUBLIC', NULL, 186, 308, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1074, 1, 110, 'COUNTRY', 'CHAD', NULL, 182, 309, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1075, 1, 110, 'COUNTRY', 'COMOROS', NULL, 221, 310, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1076, 1, 110, 'COUNTRY', 'CONGO', NULL, 183, 311, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1077, 1, 110, 'COUNTRY', 'CONGO REPUBLIC', NULL, 184, 312, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1078, 1, 110, 'COUNTRY', 'DJIBOUTI', NULL, 220, 313, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1079, 1, 110, 'COUNTRY', 'EQUATORIAL GUINEA', NULL, 187, 314, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1080, 1, 110, 'COUNTRY', 'ERITREA', NULL, 206, 315, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1081, 1, 110, 'COUNTRY', 'GABON', NULL, 180, 316, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1082, 1, 110, 'COUNTRY', 'GAMBIA,THE', NULL, 190, 317, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1083, 1, 110, 'COUNTRY', 'GHANA', NULL, 191, 318, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1084, 1, 110, 'COUNTRY', 'GUINEA', NULL, 192, 319, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1085, 1, 110, 'COUNTRY', 'GUINEA BISSAU', NULL, 205, 320, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1086, 1, 110, 'COUNTRY', 'IVORY COAST', NULL, 193, 321, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1087, 1, 110, 'COUNTRY', 'LESOTHO', NULL, 227, 322, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1088, 1, 110, 'COUNTRY', 'LIBERIA', NULL, 194, 323, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1089, 1, 110, 'COUNTRY', 'MADAGASCAR', NULL, 210, 324, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1090, 1, 110, 'COUNTRY', 'MALAWI', NULL, 211, 325, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1091, 1, 110, 'COUNTRY', 'MALI', NULL, 195, 326, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1092, 1, 110, 'COUNTRY', 'MAURITANIA', NULL, 203, 327, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1093, 1, 110, 'COUNTRY', 'MAYOTTE', NULL, 232, 328, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1094, 1, 110, 'COUNTRY', 'MOZAMBIQUE', NULL, 213, 329, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1095, 1, 110, 'COUNTRY', 'NAMIBIA', NULL, 226, 330, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1096, 1, 110, 'COUNTRY', 'NIGER', NULL, 196, 331, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1097, 1, 110, 'COUNTRY', 'NIGERIA', NULL, 197, 332, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1098, 1, 110, 'COUNTRY', 'RWANDA', NULL, 214, 333, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1099, 1, 110, 'COUNTRY', 'SAINT HELENA', NULL, 223, 334, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1100, 1, 110, 'COUNTRY', 'SAO TOME AND PRINCIPE', NULL, 178, 335, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1101, 1, 110, 'COUNTRY', 'SENEGAL', NULL, 198, 336, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1102, 1, 110, 'COUNTRY', 'SEYCHELLES', NULL, 215, 337, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1103, 1, 110, 'COUNTRY', 'SIERRA LEONE', NULL, 199, 338, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1104, 1, 110, 'COUNTRY', 'SOMALIA', NULL, 216, 339, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1105, 1, 110, 'COUNTRY', 'SUDAN', NULL, 235, 340, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1106, 1, 110, 'COUNTRY', 'SWAZILAND', NULL, 228, 341, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1107, 1, 110, 'COUNTRY', 'TANZANIA', NULL, 217, 342, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1108, 1, 110, 'COUNTRY', 'TOGO', NULL, 200, 343, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1109, 1, 110, 'COUNTRY', 'TUNISIA', NULL, 236, 344, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1110, 1, 110, 'COUNTRY', 'UGANDA', NULL, 218, 345, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1111, 1, 110, 'COUNTRY', 'ZAMBIA', NULL, 219, 346, 'N', 'N');
INSERT INTO MD_COUNTRY_GROUP_NODE (NODE_ID, GROUP_ID, PARENT_NODE_ID, NODE_TYPE, NAME_EN, NAME_TH, COUNTRY_ID, SORT_ORDER, IS_OTHERS, IS_SUMMARY) VALUES (1112, 1, 110, 'COUNTRY', 'ZIMBABWE', NULL, 185, 347, 'N', 'N');

COMMIT;

-- =====================================================================
-- AFTER: ตรวจสอบหลัง INSERT
-- =====================================================================

-- 1) นับ COUNTRY ใน 6 OTHERS bucket (ต้องได้: 2, 14, 15, 31, 3, 48)
SELECT 'AFTER - OTHERS country counts' AS phase, NODE_ID, NAME_EN,
       (SELECT COUNT(*) FROM MD_COUNTRY_GROUP_NODE c
        WHERE c.PARENT_NODE_ID = n.NODE_ID AND c.NODE_TYPE = 'COUNTRY') AS NC
FROM MD_COUNTRY_GROUP_NODE n
WHERE n.NODE_ID IN (30, 34, 79, 90, 103, 110)
ORDER BY n.NODE_ID;

-- 2) นับ country ทั้งหมดใน STD_GOV (ต้องได้ 91 + 113 = 204)
SELECT 'AFTER - STD_GOV total country count' AS phase, COUNT(DISTINCT n.COUNTRY_ID) AS CNT
FROM MD_COUNTRY_GROUP g
JOIN MD_COUNTRY_GROUP_NODE n ON n.GROUP_ID = g.GROUP_ID
WHERE g.GROUP_CODE = 'STD_GOV' AND n.NODE_TYPE = 'COUNTRY' AND n.COUNTRY_ID IS NOT NULL;

-- 3) ไม่มี duplicate COUNTRY_ID ใน STD_GOV (ต้องได้ 0 rows)
SELECT 'AFTER - STD_GOV duplicates' AS phase, n.COUNTRY_ID, COUNT(*) AS CNT
FROM MD_COUNTRY_GROUP g
JOIN MD_COUNTRY_GROUP_NODE n ON n.GROUP_ID = g.GROUP_ID
WHERE g.GROUP_CODE = 'STD_GOV' AND n.NODE_TYPE = 'COUNTRY' AND n.COUNTRY_ID IS NOT NULL
GROUP BY n.COUNTRY_ID
HAVING COUNT(*) > 1;
